spring.application.name: gatewayservicex
server.port: 8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost
spring:
  cloud:
    gateway:
      routes:
      - id: booking-service
<<<<<<< HEAD
        uri:
          lb://booking-service
=======
        uri: lb://booking-service
>>>>>>> osvaldox
        predicates:
        - Path=/bookings/**
      - id: train-service
        uri: lb://train-service
        predicates:
        - Path=/trains/**
      - id: user-service
        uri: lb://user-service
        predicates:
<<<<<<< HEAD
        - Path=/users/**         
=======
        - Path=/users/**  
      - id: user-service
        uri: lb://passenger-service
        predicates:
        - Path=/passengers/**        
>>>>>>> osvaldox
